server:
   port: 8004
   ssl:
      enabled: true
      key-store: src/main/resources/websocket-service-keystore.p12
      key-store-password: <password>
      key-store-type: PKCS12
      key-alias: websocket-service

      trust-store: src/main/resources/truststore.p12
# ðŸ”‘ Truststore (so user-service trusts Eureka's certificate)
      trust-store-password: <password>
      trust-store-type: PKCS12

spring:
   application:
      name: websocket-service

   kafka:
      bootstrap-servers: localhost:9092
      properties:
         security.protocol: PLAINTEXT
      consumer:
           group-id: webservice-service-group
           key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
           value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
           auto-offset-reset: latest
      admin:
         client-id: user-service-admin

   data:
      redis:
         host: localhost
         port: 6379
eureka:
   instance:
      hostname: localhost
      secure-port-enabled: true
      secure-port: 8004
      non-secure-port-enabled: false
      prefer-ip-address: false
      instance-id: ${spring.application.name}:${server.port}
      metadata-map:
         secure: true

   client:
      register-with-eureka: true # server itself doesnâ€™t register
      fetch-registry: true
      service-url:
         defaultZone: https://localhost:8761/eureka/